In [1]:
# carrega funcao que separa algarismos da imagem de teste
%run -i 'separa_algarismos.ipynb'

In [2]:
# carrega os classificadores salvos
from sklearn.externals import joblib
import numpy as np

clf_redeneural = joblib.load('Modelos_de_Classificacao/clf_redeneural.pkl')
clf_floresta = joblib.load('Modelos_de_Classificacao/clf_floresta.pkl')
#clf_redeneural = joblib.load('Modelos_de_Classificacao/clf_redeneural_total.pkl')
#clf_floresta = joblib.load('Modelos_de_Classificacao/clf_floresta_total.pkl')


/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [3]:
# chama a funcao para a imagem de teste
Vetores = separa_algarismos('testes/teste1.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [4]:
# teste 1
clf_floresta.predict(Vetores[0:3])

array([1, 5, 5])

In [5]:
clf_redeneural.predict(Vetores[0:3])

array([2, 5, 5])

In [6]:
#gabarito do teste 1: 2, 5, 5

In [7]:
# chama a funcao para a imagem de teste
Vetores = separa_algarismos('testes/teste2.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [8]:
clf_floresta.predict(Vetores[0:6])

array([0, 2, 3, 1, 4, 1])

In [9]:
clf_redeneural.predict(Vetores[0:6])

array([1, 2, 3, 1, 4, 1])

In [10]:
#gabarito do teste 2: 0, 2, 3, 7, 4, 1

In [11]:
# chama a funcao para a imagem de teste
Vetores = separa_algarismos('testes/teste3.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [12]:
clf_floresta.predict(Vetores[0:10])

array([5, 0, 1, 1, 3, 9, 1, 1, 9, 7])

In [13]:
clf_redeneural.predict(Vetores[0:10])

array([5, 0, 2, 1, 3, 8, 7, 6, 9, 4])

In [14]:
#gabarito do teste 3: 5, 0, 2, 1, 3, 8, 7, 6, 9, 4

In [15]:
Vetores = separa_algarismos('testes/teste4.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [16]:
clf_floresta.predict(Vetores)

array([4, 1, 4, 9, 9, 5, 4, 8, 4])

In [17]:
clf_redeneural.predict(Vetores)

array([0, 1, 4, 2, 9, 0, 1, 9, 4])

In [18]:
#gabarito do teste 4: 0, 1, 9, 2, 3, 5, 6, 8, 4

In [19]:
Vetores = separa_algarismos('testes/teste5.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [20]:
clf_floresta.predict(Vetores)

array([4, 2, 5, 1, 7, 0, 5, 9])

In [21]:
clf_redeneural.predict(Vetores)

array([4, 2, 5, 1, 7, 0, 0, 9])

In [22]:
#gabarito do teste 5: 4, 2, 5, 1, 7, 0, 8, 9

In [23]:
Vetores = separa_algarismos('testes/teste6.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [24]:
clf_floresta.predict(Vetores)

array([7, 5, 4, 4, 7])

In [25]:
clf_redeneural.predict(Vetores)

array([2, 9, 5, 4, 7])

In [26]:
#gabarito do teste 6: 2, 9, 5, 4, 7