In [1]:
# carrega funcao que separa algarismos da imagem de teste
%run -i 'separa_algarismos.ipynb'

In [2]:
# carrega os classificadores salvos
from sklearn.externals import joblib
import numpy as np

clf_redeneural = joblib.load('Modelos_de_Classificacao/clf_redeneural.pkl')
clf_floresta = joblib.load('Modelos_de_Classificacao/clf_floresta.pkl')
#clf_redeneural = joblib.load('Modelos_de_Classificacao/clf_redeneural_total.pkl')
#clf_floresta = joblib.load('Modelos_de_Classificacao/clf_floresta_total.pkl')


In [3]:
# chama a funcao para a imagem de teste
Vetores = separa_algarismos('teste1.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [4]:
# teste 1
clf_floresta.predict(Vetores[0:3])

array([2, 5, 5])

In [5]:
clf_redeneural.predict(Vetores[0:3])

array([2, 5, 5])

In [6]:
#gabarito do teste 1: 2, 5, 5

In [7]:
# chama a funcao para a imagem de teste
Vetores = separa_algarismos('teste2.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [8]:
clf_floresta.predict(Vetores[0:6])

array([0, 2, 3, 1, 1, 1])

In [9]:
clf_redeneural.predict(Vetores[0:6])

array([4, 2, 3, 1, 5, 1])

In [10]:
#gabarito do teste 2: 0, 2, 3, 7, 4, 1

In [11]:
# chama a funcao para a imagem de teste
Vetores = separa_algarismos('teste3.jpeg')

for i in np.arange(len(Vetores)):
    Vetores[i] = (-Vetores[i] + 255)/255

In [12]:
clf_floresta.predict(Vetores[0:10])

array([5, 0, 1, 4, 3, 9, 7, 1, 4, 4])

In [13]:
clf_redeneural.predict(Vetores[0:10])

array([5, 0, 2, 1, 3, 8, 7, 6, 9, 1])

In [14]:
#gabarito do teste 3: 5, 0, 2, 1, 3, 8, 7, 6, 9, 4